# Generated by Django 5.2.5 on 2025-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=8, unique=True)),
                ('long_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
