# Generated by Django 5.2.5 on 2025-08-07 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_confteam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="confteam",
            old_name="Conference",
            new_name="conference",
        ),
    ]
