# Generated by Django 6.0.1 on 2026-02-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_pickemregisterannual'),
        ('live_game_blog', '0041_remove_stadiumconfig_lights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_game_blog.team'),
        ),
    ]
