# Generated by Django 6.0.2 on 2026-02-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_alter_pick_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.pickemregisterannual'),
        ),
    ]
