# Generated by Django 4.2.7 on 2023-12-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_game_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="live_stats",
            field=models.URLField(blank=True, null=True),
        ),
    ]
