# Generated by Django 5.0 on 2024-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_game_blog", "0015_alter_scoreboard_inning_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreboard",
            name="inning_part",
            field=models.CharField(
                blank=True,
                choices=[("Top", "Top"), ("Bottom", "Bottom")],
                max_length=16,
                null=True,
            ),
        ),
    ]
