# Generated by Django 5.1.3 on 2024-12-13 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live_game_blog", "0021_game_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="fall_exhibition",
        ),
    ]
