# Generated by Django 5.1.7 on 2025-03-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_blog', '0023_game_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='is_photo_only',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
