# Generated by Django 5.2.8 on 2025-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_blog', '0028_homestadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumconfig',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
