# Generated by Django 5.2.8 on 2025-11-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_blog', '0031_game_first_pitch_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumconfig',
            name='home_dugout',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadiumconfig',
            name='lights',
            field=models.BooleanField(default=True),
        ),
    ]
