# Generated by Django 5.2.8 on 2025-11-24 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live_game_blog", "0033_alter_stadium_orientation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="first_pitch_wind_direction",
        ),
    ]
