# Generated by Django 5.2.8 on 2025-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_game_blog", "0034_remove_game_first_pitch_wind_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="first_pitch_wind_angle",
            field=models.IntegerField(null=True),
        ),
    ]
