# Generated by Django 6.0 on 2025-12-26 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live_game_blog", "0040_remove_game_stadium_game_stadium_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stadiumconfig",
            name="lights",
        ),
    ]
