# Generated by Django 6.0.2 on 2026-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_blog', '0041_remove_stadiumconfig_lights'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_conf_record',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='away_record',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_conf_record',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_record',
            field=models.CharField(blank=True, null=True),
        ),
    ]
