# Generated by Django 6.0.2 on 2026-02-20 20:43

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_blog', '0042_game_away_conf_record_game_away_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_time',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='game',
            name='neutral_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='update_time',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
