# Generated by Django 5.0.1 on 2024-01-14 02:40

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('hsgrad_year', models.IntegerField()),
                ('high_school', models.CharField(blank=True, null=True)),
                ('home_city', models.CharField(blank=True, null=True)),
                ('home_state', models.CharField(blank=True, max_length=2, null=True)),
                ('home_country', models.CharField(db_default=models.Value('USA'))),
                ('headshot', models.URLField(blank=True, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('bats', models.CharField(blank=True, choices=[('Left', 'left'), ('Right', 'right'), ('Both', 'both')], max_length=16, null=True)),
                ('throws', models.CharField(blank=True, choices=[('Left', 'left'), ('Right', 'right'), ('Both', 'both')], max_length=16, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('clock', models.IntegerField(db_default=models.Value(5))),
            ],
        ),
        migrations.CreateModel(
            name='AnnualRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_year', models.IntegerField()),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('spring_roster', models.BooleanField(blank=True, null=True)),
                ('played_in_spring', models.BooleanField(blank=True, null=True)),
                ('grey_shirt', models.BooleanField(blank=True, null=True)),
                ('granted_waiver', models.BooleanField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_tracking.player')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_event', models.CharField(choices=[('Verbal Commitment from High School', 'verbal'), ('Verbal Commitment from College', 'transfer'), ('National Letter of Intent Signed', 'nli'), ('Decommit', 'decommit'), ('Entered Transfer Portal', 'in_portal'), ('Signed Professional Contract', 'pro'), ('No Longer With Program - Other Reason', 'other')], max_length=64)),
                ('trans_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_tracking.player')),
            ],
        ),
    ]
