# Generated by Django 5.0 on 2024-01-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_game_blog", "0014_alter_team_team_name"),
        ("player_tracking", "0003_transaction_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualroster",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="live_game_blog.team",
            ),
            preserve_default=False,
        ),
    ]
