# Generated by Django 5.0 on 2024-01-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracking', '0005_alter_annualroster_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualroster',
            old_name='fall_year',
            new_name='spring_year',
        ),
    ]
