# Generated by Django 5.0.6 on 2024-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracking', '0019_alter_annualroster_status_alter_player_last_spring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualroster',
            name='status',
            field=models.CharField(choices=[('Fall Roster', 'Fall Roster'), ('Spring Roster', 'Spring Roster'), ('Not on Spring roster', 'Not on Spring roster'), ('Played but granted eligibility waiver', 'Played but granted eligibility waiver'), ('On Spring Roster but did not play', 'On Spring Roster but did not play'), ('Replaced on Spring Roster - Medical', 'Replaced on Spring Roster - Medical'), ('Redshirt with clock extension - Medical', 'Redshirt with clock extension - Medical'), ('Redshirt with clock extension - Other', 'Redshirt with clock extension - Other')], db_default='Fall Roster'),
        ),
    ]
