# Generated by Django 5.0.6 on 2024-06-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player_tracking", "0024_summerteam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summerteam",
            old_name="team",
            new_name="name",
        ),
    ]
