# Generated by Django 5.0.6 on 2024-07-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_blog', '0019_game_audio_primary_game_audio_student_and_more'),
        ('player_tracking', '0028_rename_url_summerleague_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='other_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_game_blog.team'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_event',
            field=models.CharField(choices=[('Verbal Commitment from High School', 'Verbal Commitment from High School'), ('Verbal Commitment from College', 'Verbal Commitment from College'), ('National Letter of Intent Signed', 'National Letter of Intent Signed'), ('Not Drafted', 'Not Drafted'), ('Not Signing Professional Contract', 'Not Signing Professional Contract'), ('Decommit', 'Decommit'), ('Entered Transfer Portal', 'Entered Transfer Portal'), ('Verbal Commitment to Transfer College', 'Verbal Commitment to Transfer College'), ('Attending MLB Draft Combine', 'Attending MLB Draft Combine'), ('Drafted', 'Drafted'), ('Signed Professional Contract - Undrafted', 'Signed Professional Contract - Undrafted'), ('No Longer With Program - Other Reason', 'No Longer With Program - Other Reason'), ('Not playing but with the program in another role', 'Not playing but with the program in another role'), ('Drafted former IU', 'Drafted former IU'), ('Signed Professional Contract', 'Signed Professional Contract'), ('Verbal Commitment to New College', 'Verbal Commitment to New College'), ('Entered Transfer Portal - former IU', 'Entered Transfer Portal - former IU')], max_length=64),
        ),
    ]
