# Generated by Django 5.0.7 on 2024-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "player_tracking",
            "0030_proforg_transaction_draft_round_transaction_prof_org",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mlbdraftdate",
            name="draft_complete",
            field=models.BooleanField(default=False),
        ),
    ]
