# Generated by Django 5.0.7 on 2024-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_tracking", "0031_mlbdraftdate_draft_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="first_spring",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
