# Generated by Django 5.0.7 on 2024-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player_tracking", "0033_transaction_bonus_or_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, null=True),
        ),
    ]
