# Generated by Django 5.1.4 on 2024-12-23 00:24

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_tracking", "0035_player_action_shot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accolade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_date",
                    models.DateField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("citation", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=64)),
                ("award_org", models.CharField(blank=True, max_length=64, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "annual_roster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player_tracking.annualroster",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player_tracking.player",
                    ),
                ),
            ],
        ),
    ]
