# Generated by Django 5.1.4 on 2024-12-23 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("player_tracking", "0037_alter_accolade_award_org"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["last", "first"]},
        ),
    ]
