# Generated by Django 5.1.4 on 2024-12-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracking', '0038_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualroster',
            options={'ordering': ['player', 'spring_year']},
        ),
    ]
