# Generated by Django 5.1.4 on 2024-12-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracking', '0039_alter_annualroster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accolade',
            options={'ordering': ['-award_date', 'name']},
        ),
    ]
