# Generated by Django 5.1.7 on 2025-03-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_tracking", "0041_accolade_summer_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualroster",
            name="status",
            field=models.CharField(
                choices=[
                    ("Fall Roster", "Fall Roster"),
                    ("Spring Roster", "Spring Roster"),
                    ("Not on Spring roster", "Not on Spring roster"),
                    (
                        "Played but granted eligibility waiver",
                        "Played but granted eligibility waiver",
                    ),
                    (
                        "On Spring Roster but did not play",
                        "On Spring Roster but did not play",
                    ),
                    (
                        "Medical Waiver - ending eligibility",
                        "Medical Waiver - ending eligibility",
                    ),
                    (
                        "Replaced on Spring Roster - Medical",
                        "Replaced on Spring Roster - Medical",
                    ),
                    (
                        "Redshirt with clock extension - Medical",
                        "Redshirt with clock extension - Medical",
                    ),
                    (
                        "Redshirt with clock extension - Other",
                        "Redshirt with clock extension - Other",
                    ),
                ],
                db_default="Fall Roster",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="trans_event",
            field=models.CharField(
                choices=[
                    (
                        "Verbal Commitment from High School",
                        "Verbal Commitment from High School",
                    ),
                    (
                        "Verbal Commitment from College",
                        "Verbal Commitment from College",
                    ),
                    (
                        "National Letter of Intent Signed",
                        "National Letter of Intent Signed",
                    ),
                    ("Not Drafted", "Not Drafted"),
                    (
                        "Not Signing Professional Contract",
                        "Not Signing Professional Contract",
                    ),
                    ("Decommit", "Decommit"),
                    ("Entered Transfer Portal", "Entered Transfer Portal"),
                    (
                        "Verbal Commitment to Transfer College",
                        "Verbal Commitment to Transfer College",
                    ),
                    ("Attending MLB Draft Combine", "Attending MLB Draft Combine"),
                    (
                        "Ranked MLB Draft Prospect for Next Draft",
                        "Ranked MLB Draft Prospect for Next Draft",
                    ),
                    ("Drafted", "Drafted"),
                    (
                        "Signed Professional Contract - Undrafted",
                        "Signed Professional Contract - Undrafted",
                    ),
                    (
                        "Medical Waiver - ending eligibility",
                        "Medical Waiver - ending eligibility",
                    ),
                    (
                        "No Longer With Program - Other Reason",
                        "No Longer With Program - Other Reason",
                    ),
                    (
                        "Not playing but with the program in another role",
                        "Not playing but with the program in another role",
                    ),
                    ("Drafted former IU", "Drafted former IU"),
                    ("Signed Professional Contract", "Signed Professional Contract"),
                    (
                        "Verbal Commitment to New College",
                        "Verbal Commitment to New College",
                    ),
                    (
                        "Entered Transfer Portal - former IU",
                        "Entered Transfer Portal - former IU",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
