# Generated by Django 5.2.3 on 2025-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracking', '0042_alter_annualroster_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_event',
            field=models.CharField(choices=[('Attending MLB Draft Combine', 'Attending MLB Draft Combine'), ('Decommit', 'Decommit'), ('Drafted', 'Drafted'), ('Drafted former IU', 'Drafted former IU'), ('Entered Transfer Portal', 'Entered Transfer Portal'), ('Entered Transfer Portal - former IU', 'Entered Transfer Portal - former IU'), ('Medical Waiver - ending eligibility', 'Medical Waiver - ending eligibility'), ('National Letter of Intent Signed', 'National Letter of Intent Signed'), ('No Longer With Program - Other Reason', 'No Longer With Program - Other Reason'), ('Not Drafted', 'Not Drafted'), ('Not Signing Professional Contract', 'Not Signing Professional Contract'), ('Not playing but with the program in another role', 'Not playing but with the program in another role'), ('Ranked MLB Draft Prospect for Next Draft', 'Ranked MLB Draft Prospect for Next Draft'), ('Signed Professional Contract', 'Signed Professional Contract'), ('Signed Professional Contract - Undrafted', 'Signed Professional Contract - Undrafted'), ('Verbal Commitment from College', 'Verbal Commitment from College'), ('Verbal Commitment from High School', 'Verbal Commitment from High School'), ('Verbal Commitment to Transfer College', 'Verbal Commitment to Transfer College')], max_length=64),
        ),
    ]
