# Generated by Django 5.2.3 on 2025-06-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracking', '0043_alter_transaction_trans_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='via_exhaust',
            field=models.BooleanField(default=True),
        ),
    ]
