# Generated by Django 5.0.7 on 2024-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_alter_trafficcounter_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficcounter",
            name="ip",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="trafficcounter",
            name="user_agent",
            field=models.CharField(null=True),
        ),
    ]
